league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        access_token_ttl: PT1H
        refresh_token_ttl: P1M
        enable_auth_code_grant: true
        enable_refresh_token_grant: true
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available: ['openid', 'email', 'profile']
        default: ['openid', 'email', 'profile']
    persistence:
        doctrine:
            entity_manager: default

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
